services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - yaso-network

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      # Use host.docker.internal to access host's localhost
      - DB_HOST=host.docker.internal
      # Ensure these match your local MySQL configuration
      - DB_USER=root
      - DB_PASSWORD=wod123
      - DB_NAME=yaso
    volumes:
      - ./server/uploads:/app/server/uploads
    networks:
      - yaso-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  yaso-network:
    driver: bridge
